# ====================== 
# Production version
# ======================

version: "3"

services:
  backend:
    build: ./backend
    container_name: micro_rdapps_backend_compose_docker_container
    volumes:
      - ./backend:/rchk_app_production/back-end/
    ports:
      - '3080:3080'
  frontend:
    build: ./frontend
    container_name: micro_rdapps_frontend_compose_docker_container
    volumes:
      - ./frontend:/rchk_app_production/front-end/
    ports:
      - '8080:8080'
  nginx:
    build: ./nginx
    container_name: micro_rdapps_nginx_docker_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rdapps.conf:/etc/nginx/conf.d/rdapps.conf
      - ./frontend:/rchk_app_production/front-end/
    ports:
      - '6999:80'
    depends_on:
      - frontend
      - backend

# ======================
# Develop version 
# ======================

# version: "3"

# services:
#   database:
#     build: ./database
#     container_name: micro_rdapps_db_docker_container
#     restart: always
#     volumes:
#       - ./database:/rchk_app_production/database/
#   backend:
#     build: ./backend
#     container_name: micro_rdapps_backend_compose_docker_container
#     volumes:
#       - ./backend:/rchk_app_production/back-end/
#     ports:
#       - '3080:3080'
#     depends_on:
#       - database
#     links:
#       - database
#     environment:
#       WAIT_HOSTS: database:3306
#   frontend:
#     build: ./frontend
#     container_name: micro_rdapps_frontend_compose_docker_container
#     volumes:
#       - ./frontend:/rchk_app_production/front-end/
#     ports:
#       - '8080:8080'
#   nginx:
#     build: ./nginx
#     container_name: micro_rdapps_nginx_docker_container
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./nginx/rdapps.conf:/etc/nginx/conf.d/rdapps.conf
#       - ./frontend:/rchk_app_production/front-end/
#     ports:
#       - '6999:80'
#     depends_on:
#       - frontend
#       - backend
#       - database
